services:
  dev-environment:
    build:
      context: .
      args:
        USERNAME: ${USERNAME:-default-user}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    container_name: ubuntu-dev
    hostname: dev-container
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    cgroup: host
    ports:
      - "2222:22"      # SSH on host port 2222
      - "4003:4000"    # NoMachine default port
      - "4003:4000/tcp"    # NoMachine default port
      - "4003:4000/udp"    # NoMachine default port
      - "8585:8585"    # VS Code Server (optional)
    volumes:
      - dev-home:/home/${USERNAME:-default-user}
      - ./workspace:/home/${USERNAME:-default-user}/workspace
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      # Optional: mount docker socket to use host's Docker
      # - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /run
      - /run/lock
    restart: unless-stopped
    environment:
      - container=docker
      - USER_PASSWORD=${USER_PASSWORD:-}
      - USER_PASSWORD_HASH=${USER_PASSWORD_HASH:-}
      # VS Code Server settings
      - VSCODE_PORT=${VSCODE_PORT:-8585}
      - VSCODE_HOST=${VSCODE_HOST:-0.0.0.0}
      - VSCODE_TOKEN=${VSCODE_TOKEN:-}
      - VSCODE_TOKEN_FILE=${VSCODE_TOKEN_FILE:-}
      - VSCODE_SERVER_DATA_DIR=${VSCODE_SERVER_DATA_DIR:-}
      - VSCODE_SERVER_BASE_PATH=${VSCODE_SERVER_BASE_PATH:-}
      - VSCODE_SOCKET_PATH=${VSCODE_SOCKET_PATH:-}
      - VSCODE_VERBOSE=${VSCODE_VERBOSE:-}
      - VSCODE_LOG_LEVEL=${VSCODE_LOG_LEVEL:-}
      - VSCODE_CLI_DATA_DIR=${VSCODE_CLI_DATA_DIR:-}

volumes:
  dev-home:
    driver: local
